default:
  image: maven:3-openjdk-8
  # Cache downloaded dependencies and plugins between builds.
  # The key here separates one cache per branch/tag ($CI_COMMIT_REF_SLUG)
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository

stages:
  - build
  - verify
  - publish

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_ARGS: >-
    --batch-mode
    --errors
    --fail-at-end
    --no-transfer-progress
    --show-version
    --update-snapshots
    -DdeployAtEnd=true

  BUILD_TYPE:
    description: "Select build type. While snapshot publishes artifacts to repository 'as is', release also bumps artifacts' version before and after they are published."
    value: "snapshot"
    options:
      - "snapshot"
      - "release"

  RELEASE_PROPERTIES:
    description: "Set release.properties for maven-release-plugin. Only used when BUILD_TYPE 'release' is selected."
    value: |-
      scm.tag=my-proj-1.2
      project.rel.org.myCompany:projectA=1.2
      project.dev.org.myCompany:projectA=1.3-SNAPSHOT

maven-install:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUILD_TYPE == 'snapshot'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - mvn --settings $CI_MAVEN_SETTINGS $MAVEN_ARGS install
  artifacts:
    when: always
    reports:
      # Store JUnit reports (recursive pattern for multi-module projects)
      junit:
        - "**/target/*-reports/TEST-*.xml"

maven-verify-db-it:
  stage: verify
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUILD_TYPE == 'snapshot'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  parallel:
    matrix:
      - MAVEN_PROFILE: jpa
      - MAVEN_PROFILE: hibernate3
      - MAVEN_PROFILE: hibernate5
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlays.
    DOCKER_DRIVER: overlay2
  script:
    - cd discussment-db-it
    - mvn --settings $CI_MAVEN_SETTINGS $MAVEN_ARGS -P$MAVEN_PROFILE verify
  artifacts:
    when: always
    reports:
      # Store JUnit reports (recursive pattern for multi-module projects)
      junit:
        - "**/target/*-reports/TEST-*.xml"

maven-deploy:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUILD_TYPE == 'snapshot'
  script:
    - mvn --settings $CI_MAVEN_SETTINGS $MAVEN_ARGS -Dmaven.test.skip=true -Dmaven.install.skip=true deploy

maven-release:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUILD_TYPE == 'release'
  before_script:
    - |
      if [[ ! -z $RELEASE_PROPERTIES ]]; then
        echo $RELEASE_PROPERTIES > release.properties
      fi
  script:
    - mvn --settings $CI_MAVEN_SETTINGS $MAVEN_ARGS release:prepare -DdryRun
    - mvn --settings $CI_MAVEN_SETTINGS $MAVEN_ARGS release:perform -DdryRun
